# application.yml
spring:
  application:
    name: easyonbid

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/easyonbid
    username: root
    password: 1234

  thymeleaf:
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
    cache: false

# scheduler
#  task:
#    scheduling:
#      pool:
#        size: 5
#      thread-name-prefix: easyonbid-scheduler-

# mybatis settings
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.easyonbid.entity
  configuration:
    map-underscore-to-camel-case: true

# api url / key settings
openapi:
  easyonbid:
    url: "http://openapi.onbid.co.kr/openapi/services/KamcoPblsalThingInquireSvc/getKamcoPbctCltrList"
    serviceKey: "273f45187071c8be25359787b100033ecd7addb7ab2b533878d80dd80dcf4fdb"

#scheduler settings
#scheduler:
#  easyonbid:
#  enabled: ture
#  cron: 0 0 3 * * *
#  max-pages: 55
#  rows-per-page: 200
